apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
spec:
  rules:
  - host: <website>
    http:
      paths:
      - backend:
          serviceName: prometheus-grafana
          servicePort: 80

